### ISSUE TITLE
switch to aws-iam-authenticator 0.5.7 breaks EKS runs.

### ISSUE THREAD

**Issue by bwang221** [kodermax/kubectl-aws-eks#22]
aws-iam-authenticator changed behavior since aws-iam-authenticator 0.5.4,  but default  is still client.authentication.k8s.io/v1appha, which does not work with 0.5.4+

The change made today breaks lots of people's pipeline I believe, is there a way to go back to an older version that works?

**Comment by Hacks4Snacks** [comment]
@bwang221 

In the most recent merge you can define versions for kubectl and aws-iam-authenticator via ENV variables. Example below:

      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-app
          IMAGE_TAG: ${{ github.sha }
          KUBECTL_VERSION: "v1.22.0"
          IAM_VERSION: "0.5.4"
        with:
          args: set image deployment/$ECR_REPOSITORY

**Comment by bwang221** [comment]
Thanks for quick response, yes, that fixes the issue, need to change all repos

**Comment by kosta1221** [comment]
Yes, this is unfortunate indeed. I think that the only way in which nobody had to change a thing would be if this action would explicitly use a version of kubectl lower than 1.24 instead of defaulting on the latest stable which is now 1.24.

The change in #20 is great because it allows control over the version of kubectl and aws-iam-authenticator. So, does everybody who used this action until now have to add these 2 environment variables to actions usage? -Yes

Do kubeconfigs have to change? -Not necessarily, and that's indeed great. There really was no better way.

**Comment by bwang221** [comment]
Thanks again,  agree it is good for the long.

It does break lots of stuff.

A side question kind of unrelated.  how to achieve the equivalent of the following with this action?

% cat afile.yml | kubectl apply -f -

**Comment by kosta1221** [comment]
@bwang221 Why not just apply the file?

`kubectl apply -f afile.yml`
