### ISSUE TITLE
Docker build fail - curl points to non existent files

### ISSUE THREAD

**Issue by Kajpio** [kodermax/kubectl-aws-eks#38]
In the initial step of the GitHub actions, the Dockerfile is built based on the Dockerfile image.

The 4th step, which would normally download kubectl and aws-iam-authentificator doesn't seem to have the correct links, resulting in the docker build falling and the GitHub action.

Possible fixes:
* Replace kubectl download link
* Replace aws-iam-authentification download link

**Comment by alisonfrancisco** [comment]
same here

**Comment by flxdot** [comment]
Is this some sort of caching issue?

Because [this change](https://github.com/kodermax/kubectl-aws-eks/commit/7e223308593f74c42b45782d230783715e131d51) is legit. I tried building the image with the fix, and it works:

<img width="1763" alt="Screenshot 2023-11-29 at 13 50 03" src="https://github.com/kodermax/kubectl-aws-eks/assets/35657654/9dd5c33b-60c5-4b4c-af83-92de73d5d27d">

And I can see in our CI logs, that it still uses `latest`: 
<img width="1202" alt="Screenshot 2023-11-29 at 13 48 03" src="https://github.com/kodermax/kubectl-aws-eks/assets/35657654/fa54e894-3239-4cee-a3f4-17d94223cfad">

**Comment by alisonfrancisco** [comment]
it looks related to this closed issue 
https://github.com/kodermax/kubectl-aws-eks/issues/29

**Comment by alisonfrancisco** [comment]
the dockerfile builds normaly on my device

**Comment by ridoo** [comment]
> source seems to be this: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/657

I guess, this is true. From a comment:

> From the looks of it, the create-release workflow exists but hasn't been run yet?
> But the release process seems to dictate that this is something to be done manually by a human as part of the release process.

**Comment by topogigiovanni** [comment]
I noticed that I was using the master branch when switching to main, it worked perfectly 🙏 

before: kodermax/kubectl-aws-eks@master
after: kodermax/kubectl-aws-eks@main

**Comment by alisonfrancisco** [comment]
wow, true. is this a documentation issue?
i copied from somewhere when i was defining my worflows and it was master the branch set.
but since the main is the default from the repo and it is ahead of the master, ir looks like there is some kind of misplace.
recalling now, i also had problem with the name os the environment variable KUBE_CONFIG_DATA , there was 2 different declarations on the readme.

anyway, thanks

**Comment by pietrobolcato** [comment]
> I noticed that I was using the master branch when switching to main, it worked perfectly 🙏
> 
> before: kodermax/kubectl-aws-eks@master after: kodermax/kubectl-aws-eks@main

Works for me as well, thanks so much 🙏

**Comment by ridoo** [comment]
Does this make any sense? [`main` still `curl`ing the same request](https://github.com/kodermax/kubectl-aws-eks/blob/7e223308593f74c42b45782d230783715e131d51/Dockerfile#L4) against the same `https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl`

I think, in the meantime someone actually placed the binaries at the right location :)

**Comment by kodermax** [comment]
The problem happened on the aws-iam-authenticator side; in the latest version they did not prepare packages for Linux systems. I also updated the master branch.

**Comment by Kajpio** [comment]
Thanks for the reactivity and the fix! Works for me on both branches 🙏🏿
